/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as OnboardingVerifyEmailImport } from './routes/onboarding/verify-email'
import { Route as OnboardingPersonalProfessionalInformationImport } from './routes/onboarding/personal-professional-information'
import { Route as OnboardingInfoCardImport } from './routes/onboarding/info-card'
import { Route as OnboardingCreateAccountImport } from './routes/onboarding/create-account'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingVerifyEmailRoute = OnboardingVerifyEmailImport.update({
  id: '/onboarding/verify-email',
  path: '/onboarding/verify-email',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingPersonalProfessionalInformationRoute =
  OnboardingPersonalProfessionalInformationImport.update({
    id: '/onboarding/personal-professional-information',
    path: '/onboarding/personal-professional-information',
    getParentRoute: () => rootRoute,
  } as any)

const OnboardingInfoCardRoute = OnboardingInfoCardImport.update({
  id: '/onboarding/info-card',
  path: '/onboarding/info-card',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingCreateAccountRoute = OnboardingCreateAccountImport.update({
  id: '/onboarding/create-account',
  path: '/onboarding/create-account',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/onboarding/create-account': {
      id: '/onboarding/create-account'
      path: '/onboarding/create-account'
      fullPath: '/onboarding/create-account'
      preLoaderRoute: typeof OnboardingCreateAccountImport
      parentRoute: typeof rootRoute
    }
    '/onboarding/info-card': {
      id: '/onboarding/info-card'
      path: '/onboarding/info-card'
      fullPath: '/onboarding/info-card'
      preLoaderRoute: typeof OnboardingInfoCardImport
      parentRoute: typeof rootRoute
    }
    '/onboarding/personal-professional-information': {
      id: '/onboarding/personal-professional-information'
      path: '/onboarding/personal-professional-information'
      fullPath: '/onboarding/personal-professional-information'
      preLoaderRoute: typeof OnboardingPersonalProfessionalInformationImport
      parentRoute: typeof rootRoute
    }
    '/onboarding/verify-email': {
      id: '/onboarding/verify-email'
      path: '/onboarding/verify-email'
      fullPath: '/onboarding/verify-email'
      preLoaderRoute: typeof OnboardingVerifyEmailImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/onboarding/create-account': typeof OnboardingCreateAccountRoute
  '/onboarding/info-card': typeof OnboardingInfoCardRoute
  '/onboarding/personal-professional-information': typeof OnboardingPersonalProfessionalInformationRoute
  '/onboarding/verify-email': typeof OnboardingVerifyEmailRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/onboarding/create-account': typeof OnboardingCreateAccountRoute
  '/onboarding/info-card': typeof OnboardingInfoCardRoute
  '/onboarding/personal-professional-information': typeof OnboardingPersonalProfessionalInformationRoute
  '/onboarding/verify-email': typeof OnboardingVerifyEmailRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/onboarding/create-account': typeof OnboardingCreateAccountRoute
  '/onboarding/info-card': typeof OnboardingInfoCardRoute
  '/onboarding/personal-professional-information': typeof OnboardingPersonalProfessionalInformationRoute
  '/onboarding/verify-email': typeof OnboardingVerifyEmailRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/onboarding/create-account'
    | '/onboarding/info-card'
    | '/onboarding/personal-professional-information'
    | '/onboarding/verify-email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/onboarding/create-account'
    | '/onboarding/info-card'
    | '/onboarding/personal-professional-information'
    | '/onboarding/verify-email'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/onboarding/create-account'
    | '/onboarding/info-card'
    | '/onboarding/personal-professional-information'
    | '/onboarding/verify-email'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  OnboardingCreateAccountRoute: typeof OnboardingCreateAccountRoute
  OnboardingInfoCardRoute: typeof OnboardingInfoCardRoute
  OnboardingPersonalProfessionalInformationRoute: typeof OnboardingPersonalProfessionalInformationRoute
  OnboardingVerifyEmailRoute: typeof OnboardingVerifyEmailRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  OnboardingCreateAccountRoute: OnboardingCreateAccountRoute,
  OnboardingInfoCardRoute: OnboardingInfoCardRoute,
  OnboardingPersonalProfessionalInformationRoute:
    OnboardingPersonalProfessionalInformationRoute,
  OnboardingVerifyEmailRoute: OnboardingVerifyEmailRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/onboarding/create-account",
        "/onboarding/info-card",
        "/onboarding/personal-professional-information",
        "/onboarding/verify-email"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/onboarding/create-account": {
      "filePath": "onboarding/create-account.tsx"
    },
    "/onboarding/info-card": {
      "filePath": "onboarding/info-card.tsx"
    },
    "/onboarding/personal-professional-information": {
      "filePath": "onboarding/personal-professional-information.tsx"
    },
    "/onboarding/verify-email": {
      "filePath": "onboarding/verify-email.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
