/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings/route'
import { Route as OnboardingRouteImport } from './routes/onboarding/route'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteImport } from './routes/auth/route'
import { Route as AppointmentsRouteImport } from './routes/appointments/route'
import { Route as IndexImport } from './routes/index'
import { Route as OnboardingVerifyEmailImport } from './routes/onboarding/verify-email'
import { Route as OnboardingPersonalProfessionalInformationImport } from './routes/onboarding/personal-professional-information'
import { Route as OnboardingOnboardingStepsImport } from './routes/onboarding/onboarding-steps'
import { Route as OnboardingCreateAccountImport } from './routes/onboarding/create-account'
import { Route as OnboardingCompletionImport } from './routes/onboarding/completion'
import { Route as AuthResetPasswordImport } from './routes/auth/reset-password'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AuthForgotPasswordImport } from './routes/auth/forgot-password'

// Create/Update Routes

const SettingsRouteRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingRouteRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AuthRouteRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AppointmentsRouteRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingVerifyEmailRoute = OnboardingVerifyEmailImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => OnboardingRouteRoute,
} as any)

const OnboardingPersonalProfessionalInformationRoute =
  OnboardingPersonalProfessionalInformationImport.update({
    id: '/personal-professional-information',
    path: '/personal-professional-information',
    getParentRoute: () => OnboardingRouteRoute,
  } as any)

const OnboardingOnboardingStepsRoute = OnboardingOnboardingStepsImport.update({
  id: '/onboarding-steps',
  path: '/onboarding-steps',
  getParentRoute: () => OnboardingRouteRoute,
} as any)

const OnboardingCreateAccountRoute = OnboardingCreateAccountImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => OnboardingRouteRoute,
} as any)

const OnboardingCompletionRoute = OnboardingCompletionImport.update({
  id: '/completion',
  path: '/completion',
  getParentRoute: () => OnboardingRouteRoute,
} as any)

const AuthResetPasswordRoute = AuthResetPasswordImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordImport
      parentRoute: typeof AuthRouteImport
    }
    '/onboarding/completion': {
      id: '/onboarding/completion'
      path: '/completion'
      fullPath: '/onboarding/completion'
      preLoaderRoute: typeof OnboardingCompletionImport
      parentRoute: typeof OnboardingRouteImport
    }
    '/onboarding/create-account': {
      id: '/onboarding/create-account'
      path: '/create-account'
      fullPath: '/onboarding/create-account'
      preLoaderRoute: typeof OnboardingCreateAccountImport
      parentRoute: typeof OnboardingRouteImport
    }
    '/onboarding/onboarding-steps': {
      id: '/onboarding/onboarding-steps'
      path: '/onboarding-steps'
      fullPath: '/onboarding/onboarding-steps'
      preLoaderRoute: typeof OnboardingOnboardingStepsImport
      parentRoute: typeof OnboardingRouteImport
    }
    '/onboarding/personal-professional-information': {
      id: '/onboarding/personal-professional-information'
      path: '/personal-professional-information'
      fullPath: '/onboarding/personal-professional-information'
      preLoaderRoute: typeof OnboardingPersonalProfessionalInformationImport
      parentRoute: typeof OnboardingRouteImport
    }
    '/onboarding/verify-email': {
      id: '/onboarding/verify-email'
      path: '/verify-email'
      fullPath: '/onboarding/verify-email'
      preLoaderRoute: typeof OnboardingVerifyEmailImport
      parentRoute: typeof OnboardingRouteImport
    }
  }
}

// Create and export the route tree

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingCompletionRoute: typeof OnboardingCompletionRoute
  OnboardingCreateAccountRoute: typeof OnboardingCreateAccountRoute
  OnboardingOnboardingStepsRoute: typeof OnboardingOnboardingStepsRoute
  OnboardingPersonalProfessionalInformationRoute: typeof OnboardingPersonalProfessionalInformationRoute
  OnboardingVerifyEmailRoute: typeof OnboardingVerifyEmailRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingCompletionRoute: OnboardingCompletionRoute,
  OnboardingCreateAccountRoute: OnboardingCreateAccountRoute,
  OnboardingOnboardingStepsRoute: OnboardingOnboardingStepsRoute,
  OnboardingPersonalProfessionalInformationRoute:
    OnboardingPersonalProfessionalInformationRoute,
  OnboardingVerifyEmailRoute: OnboardingVerifyEmailRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRouteRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/settings': typeof SettingsRouteRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/onboarding/completion': typeof OnboardingCompletionRoute
  '/onboarding/create-account': typeof OnboardingCreateAccountRoute
  '/onboarding/onboarding-steps': typeof OnboardingOnboardingStepsRoute
  '/onboarding/personal-professional-information': typeof OnboardingPersonalProfessionalInformationRoute
  '/onboarding/verify-email': typeof OnboardingVerifyEmailRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRouteRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/settings': typeof SettingsRouteRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/onboarding/completion': typeof OnboardingCompletionRoute
  '/onboarding/create-account': typeof OnboardingCreateAccountRoute
  '/onboarding/onboarding-steps': typeof OnboardingOnboardingStepsRoute
  '/onboarding/personal-professional-information': typeof OnboardingPersonalProfessionalInformationRoute
  '/onboarding/verify-email': typeof OnboardingVerifyEmailRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRouteRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/settings': typeof SettingsRouteRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/onboarding/completion': typeof OnboardingCompletionRoute
  '/onboarding/create-account': typeof OnboardingCreateAccountRoute
  '/onboarding/onboarding-steps': typeof OnboardingOnboardingStepsRoute
  '/onboarding/personal-professional-information': typeof OnboardingPersonalProfessionalInformationRoute
  '/onboarding/verify-email': typeof OnboardingVerifyEmailRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/onboarding/completion'
    | '/onboarding/create-account'
    | '/onboarding/onboarding-steps'
    | '/onboarding/personal-professional-information'
    | '/onboarding/verify-email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/onboarding/completion'
    | '/onboarding/create-account'
    | '/onboarding/onboarding-steps'
    | '/onboarding/personal-professional-information'
    | '/onboarding/verify-email'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/onboarding/completion'
    | '/onboarding/create-account'
    | '/onboarding/onboarding-steps'
    | '/onboarding/personal-professional-information'
    | '/onboarding/verify-email'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRouteRoute: typeof AppointmentsRouteRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRoute
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRouteRoute: AppointmentsRouteRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRoute,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/appointments",
        "/auth",
        "/dashboard",
        "/onboarding",
        "/settings"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/appointments": {
      "filePath": "appointments/route.tsx"
    },
    "/auth": {
      "filePath": "auth/route.tsx",
      "children": [
        "/auth/forgot-password",
        "/auth/login",
        "/auth/reset-password"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard/route.tsx"
    },
    "/onboarding": {
      "filePath": "onboarding/route.tsx",
      "children": [
        "/onboarding/completion",
        "/onboarding/create-account",
        "/onboarding/onboarding-steps",
        "/onboarding/personal-professional-information",
        "/onboarding/verify-email"
      ]
    },
    "/settings": {
      "filePath": "settings/route.tsx"
    },
    "/auth/forgot-password": {
      "filePath": "auth/forgot-password.tsx",
      "parent": "/auth"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx",
      "parent": "/auth"
    },
    "/auth/reset-password": {
      "filePath": "auth/reset-password.tsx",
      "parent": "/auth"
    },
    "/onboarding/completion": {
      "filePath": "onboarding/completion.tsx",
      "parent": "/onboarding"
    },
    "/onboarding/create-account": {
      "filePath": "onboarding/create-account.tsx",
      "parent": "/onboarding"
    },
    "/onboarding/onboarding-steps": {
      "filePath": "onboarding/onboarding-steps.tsx",
      "parent": "/onboarding"
    },
    "/onboarding/personal-professional-information": {
      "filePath": "onboarding/personal-professional-information.tsx",
      "parent": "/onboarding"
    },
    "/onboarding/verify-email": {
      "filePath": "onboarding/verify-email.tsx",
      "parent": "/onboarding"
    }
  }
}
ROUTE_MANIFEST_END */
