/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding/route'
import { Route as IndexImport } from './routes/index'
import { Route as OnboardingVerifyEmailImport } from './routes/onboarding/verify-email'
import { Route as OnboardingPersonalProfessionalInformationImport } from './routes/onboarding/personal-professional-information'
import { Route as OnboardingOnboardingStepsImport } from './routes/onboarding/onboarding-steps'
import { Route as OnboardingInfoCardImport } from './routes/onboarding/info-card'
import { Route as OnboardingCreateAccountImport } from './routes/onboarding/create-account'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingRouteRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingVerifyEmailRoute = OnboardingVerifyEmailImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => OnboardingRouteRoute,
} as any)

const OnboardingPersonalProfessionalInformationRoute =
  OnboardingPersonalProfessionalInformationImport.update({
    id: '/personal-professional-information',
    path: '/personal-professional-information',
    getParentRoute: () => OnboardingRouteRoute,
  } as any)

const OnboardingOnboardingStepsRoute = OnboardingOnboardingStepsImport.update({
  id: '/onboarding-steps',
  path: '/onboarding-steps',
  getParentRoute: () => OnboardingRouteRoute,
} as any)

const OnboardingInfoCardRoute = OnboardingInfoCardImport.update({
  id: '/info-card',
  path: '/info-card',
  getParentRoute: () => OnboardingRouteRoute,
} as any)

const OnboardingCreateAccountRoute = OnboardingCreateAccountImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => OnboardingRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/onboarding/create-account': {
      id: '/onboarding/create-account'
      path: '/create-account'
      fullPath: '/onboarding/create-account'
      preLoaderRoute: typeof OnboardingCreateAccountImport
      parentRoute: typeof OnboardingRouteImport
    }
    '/onboarding/info-card': {
      id: '/onboarding/info-card'
      path: '/info-card'
      fullPath: '/onboarding/info-card'
      preLoaderRoute: typeof OnboardingInfoCardImport
      parentRoute: typeof OnboardingRouteImport
    }
    '/onboarding/onboarding-steps': {
      id: '/onboarding/onboarding-steps'
      path: '/onboarding-steps'
      fullPath: '/onboarding/onboarding-steps'
      preLoaderRoute: typeof OnboardingOnboardingStepsImport
      parentRoute: typeof OnboardingRouteImport
    }
    '/onboarding/personal-professional-information': {
      id: '/onboarding/personal-professional-information'
      path: '/personal-professional-information'
      fullPath: '/onboarding/personal-professional-information'
      preLoaderRoute: typeof OnboardingPersonalProfessionalInformationImport
      parentRoute: typeof OnboardingRouteImport
    }
    '/onboarding/verify-email': {
      id: '/onboarding/verify-email'
      path: '/verify-email'
      fullPath: '/onboarding/verify-email'
      preLoaderRoute: typeof OnboardingVerifyEmailImport
      parentRoute: typeof OnboardingRouteImport
    }
  }
}

// Create and export the route tree

interface OnboardingRouteRouteChildren {
  OnboardingCreateAccountRoute: typeof OnboardingCreateAccountRoute
  OnboardingInfoCardRoute: typeof OnboardingInfoCardRoute
  OnboardingOnboardingStepsRoute: typeof OnboardingOnboardingStepsRoute
  OnboardingPersonalProfessionalInformationRoute: typeof OnboardingPersonalProfessionalInformationRoute
  OnboardingVerifyEmailRoute: typeof OnboardingVerifyEmailRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingCreateAccountRoute: OnboardingCreateAccountRoute,
  OnboardingInfoCardRoute: OnboardingInfoCardRoute,
  OnboardingOnboardingStepsRoute: OnboardingOnboardingStepsRoute,
  OnboardingPersonalProfessionalInformationRoute:
    OnboardingPersonalProfessionalInformationRoute,
  OnboardingVerifyEmailRoute: OnboardingVerifyEmailRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding/create-account': typeof OnboardingCreateAccountRoute
  '/onboarding/info-card': typeof OnboardingInfoCardRoute
  '/onboarding/onboarding-steps': typeof OnboardingOnboardingStepsRoute
  '/onboarding/personal-professional-information': typeof OnboardingPersonalProfessionalInformationRoute
  '/onboarding/verify-email': typeof OnboardingVerifyEmailRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding/create-account': typeof OnboardingCreateAccountRoute
  '/onboarding/info-card': typeof OnboardingInfoCardRoute
  '/onboarding/onboarding-steps': typeof OnboardingOnboardingStepsRoute
  '/onboarding/personal-professional-information': typeof OnboardingPersonalProfessionalInformationRoute
  '/onboarding/verify-email': typeof OnboardingVerifyEmailRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding/create-account': typeof OnboardingCreateAccountRoute
  '/onboarding/info-card': typeof OnboardingInfoCardRoute
  '/onboarding/onboarding-steps': typeof OnboardingOnboardingStepsRoute
  '/onboarding/personal-professional-information': typeof OnboardingPersonalProfessionalInformationRoute
  '/onboarding/verify-email': typeof OnboardingVerifyEmailRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/login'
    | '/onboarding/create-account'
    | '/onboarding/info-card'
    | '/onboarding/onboarding-steps'
    | '/onboarding/personal-professional-information'
    | '/onboarding/verify-email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/login'
    | '/onboarding/create-account'
    | '/onboarding/info-card'
    | '/onboarding/onboarding-steps'
    | '/onboarding/personal-professional-information'
    | '/onboarding/verify-email'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/login'
    | '/onboarding/create-account'
    | '/onboarding/info-card'
    | '/onboarding/onboarding-steps'
    | '/onboarding/personal-professional-information'
    | '/onboarding/verify-email'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/onboarding",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/onboarding": {
      "filePath": "onboarding/route.tsx",
      "children": [
        "/onboarding/create-account",
        "/onboarding/info-card",
        "/onboarding/onboarding-steps",
        "/onboarding/personal-professional-information",
        "/onboarding/verify-email"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/onboarding/create-account": {
      "filePath": "onboarding/create-account.tsx",
      "parent": "/onboarding"
    },
    "/onboarding/info-card": {
      "filePath": "onboarding/info-card.tsx",
      "parent": "/onboarding"
    },
    "/onboarding/onboarding-steps": {
      "filePath": "onboarding/onboarding-steps.tsx",
      "parent": "/onboarding"
    },
    "/onboarding/personal-professional-information": {
      "filePath": "onboarding/personal-professional-information.tsx",
      "parent": "/onboarding"
    },
    "/onboarding/verify-email": {
      "filePath": "onboarding/verify-email.tsx",
      "parent": "/onboarding"
    }
  }
}
ROUTE_MANIFEST_END */
